# Generated by Django 6.0.7 on 2026-08-05 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schools", "0002_remove_school_is_deleted"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("SUPER_ADMIN", "Super Administrator"),
                            ("SCHOOL_ADMIN", "School Administrator"),
                            ("PRINCIPAL", "Principal"),
                            ("VICE_PRINCIPAL", "Vice Principal"),
                            ("REGISTRAR", "Registrar"),
                            ("TEACHER", "Teacher"),
                            ("ACCOUNTANT", "Accountant"),
                            ("LIBRARIAN", "Librarian"),
                            ("PARENT", "Parent"),
                            ("STUDENT", "Student"),
                        ],
                        default="TEACHER",
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="profiles/"),
                ),
                ("employee_id", models.CharField(blank=True, max_length=30)),
                ("department", models.CharField(blank=True, max_length=100)),
                ("is_school_admin", models.BooleanField(default=False)),
                (
                    "role",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.role",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schools.school",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
