# Generated by Django 6.0.7

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_finance_integrity_constraints"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="feestructure",
            unique_together=set(),
        ),
    ]
