# Generated by Django 6.0.7 on 2026-07-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_student_admission_date_student_current_session_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="graduation_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="graduation_remark",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="student",
            name="graduation_session",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
