# Generated by Django 6.0.7 on 2026-07-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_student_graduation_date_student_graduation_remark_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="graduation_reason",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
