# Generated by Django 6.0.7 on 2026-07-27 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_subject_classsubject"),
        ("students", "0005_graduationhistory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="graduationhistory",
            name="graduated_from",
        ),
        migrations.AddField(
            model_name="graduationhistory",
            name="graduated_from",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="academics.schoolclass",
            ),
        ),
        migrations.AddField(
            model_name="graduationhistory",
            name="rolled_back",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="graduationhistory",
            name="graduation_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="graduationhistory",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="graduation_records",
                to="students.student",
            ),
        ),
    ]
