# Generated by Django 6.0.7 on 2026-07-27 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_subject_classsubject"),
        ("students", "0006_remove_graduationhistory_graduated_class_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="graduationhistory",
            options={"ordering": ["-graduation_date"]},
        ),
        migrations.AlterField(
            model_name="graduationhistory",
            name="graduated_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="academics.schoolclass",
            ),
        ),
    ]
