# Generated by Django 6.0.7 on 2026-07-27 23:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_subject_classsubject"),
        ("schools", "0002_remove_school_is_deleted"),
        ("students", "0008_transferhistory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transferhistory",
            name="approved_by",
        ),
        migrations.AddField(
            model_name="transferhistory",
            name="transferred_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_transfers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="WithdrawalHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("TRANSFER", "Transferred to Another School"),
                            ("FINANCIAL", "Financial Reasons"),
                            ("ILLNESS", "Illness"),
                            ("DISCIPLINE", "Disciplinary Action"),
                            ("GRADUATED", "Graduated"),
                            ("DECEASED", "Deceased"),
                            ("PARENT_REQUEST", "Parent Request"),
                            ("VOLUNTARY", "Voluntary Withdrawal"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=30,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("withdrawal_date", models.DateTimeField(auto_now_add=True)),
                ("reinstated", models.BooleanField(default=False)),
                ("reinstated_date", models.DateTimeField(blank=True, null=True)),
                (
                    "from_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="withdrawals_from",
                        to="academics.schoolclass",
                    ),
                ),
                (
                    "from_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="withdrawals_from_session",
                        to="academics.academicsession",
                    ),
                ),
                (
                    "reinstated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_reinstatements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawal_history",
                        to="schools.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawal_history",
                        to="students.student",
                    ),
                ),
                (
                    "withdrawn_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_withdrawals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Withdrawal History",
                "verbose_name_plural": "Withdrawal History",
                "ordering": ["-withdrawal_date"],
            },
        ),
    ]
