# Generated by Django 6.0.7 on 2026-07-28 07:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_subject_classsubject"),
        ("schools", "0002_remove_school_is_deleted"),
        ("students", "0009_remove_transferhistory_approved_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpulsionHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("DISCIPLINE", "Gross Misconduct"),
                            ("CRIMINAL", "Criminal Activity"),
                            ("VIOLENCE", "Violent Behaviour"),
                            ("EXAM", "Repeated Examination Malpractice"),
                            ("FRAUD", "Fraudulent Admission"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=30,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("expulsion_date", models.DateTimeField(auto_now_add=True)),
                (
                    "expelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_expulsions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="academics.schoolclass",
                    ),
                ),
                (
                    "from_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="academics.academicsession",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expulsion_history",
                        to="schools.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expulsion_history",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expulsion History",
                "verbose_name_plural": "Expulsion History",
                "ordering": ["-expulsion_date"],
            },
        ),
    ]
