# Generated by Django 6.0.7 on 2026-08-13 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_subject_classsubject"),
        ("schools", "0002_remove_school_is_deleted"),
        ("students", "0011_student_discipline_reason_student_suspension_end_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="promotionhistory",
            name="term",
            field=models.ForeignKey(
                blank=True,
                help_text="Academic term during which the promotion decision was made.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="promotion_history",
                to="academics.term",
            ),
        ),
        migrations.AlterField(
            model_name="promotionhistory",
            name="academic_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promotion_history",
                to="academics.academicsession",
            ),
        ),
        migrations.AlterField(
            model_name="promotionhistory",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_student_promotions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="promotionhistory",
            index=models.Index(
                fields=["school", "academic_session", "term"],
                name="students_pr_school__e67be3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="promotionhistory",
            index=models.Index(
                fields=["student", "academic_session"],
                name="students_pr_student_c6b6d9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="promotionhistory",
            index=models.Index(
                fields=["from_class", "to_class"], name="students_pr_from_cl_5ab723_idx"
            ),
        ),
    ]
