# Generated by Django 6.0.7 on 2026-08-14 15:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancesession",
            name="attendance_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
