# Generated by Django 6.0.7 on 2026-07-25 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="school",
            name="is_deleted",
        ),
    ]
