# Generated by Django 6.0.7 on 2026-08-29 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="is_deleted",
        ),
    ]
